title: dsmHack Hacker Guide
baseURL: /
params:
  layout_style: overflow
  palette: blue
  header:
    title: Hacker On-Boarding
    tagline: Let's do some good!
    profile_img: images/dsmhack.png
    bg: dark
    has_nav: true
    has_social: true
  footer:
    content: '&copy; All rights reserved.'
    links:
      - text: Made with Stackbit
        url: 'https://www.stackbit.com'
        new_window: true
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
