---
label: Config
hide_body: true
fields:
- type: text
  name: title
  label: Title
  description: Site title
  config:
    required: true
- type: text
  name: baseURL
  label: Base URL
  description: Hostname (and path) to the root
  hidden: true
- type: field_group
  name: params
  label: Params
  description: Site parameters
  config:
    required: true
  fields:
  - type: file
    name: favicon
    label: favicon
    description: The favicon for the site
  - name: primary_logo
    type: file
    config:
      maxSize: 250
    label: Primary Logo
    description: The logo image used on large screens.
  - name: mobile_logo
    type: file
    config:
      maxSize: 250
    label: Mobile Logo
    description: The logo image used on small screens.
  - name: social
    type: field_group_list
    fields:
    - name: icon
      type: text
      config:
        required: false
      label: icon
    - name: url
      type: text
      config:
        required: false
      label: url
    config:
      min: 
      max: 
      labelField: icon
    label: Social Links
    description: Links to social media sites.
  - type: select
    name: palette
    label: Color Palette
    description: The color palette used for the page
    config:
      required: true
      source:
        type: custom
      options:
      - blue
      - green
      - purple
  - type: field_group
    name: palettes
    label: Palettes
    hidden: true
    fields:
    - type: field_group
      name: blue
      label: Blue
      fields:
      - type: include
        name: include_palette
        label: Palette
        template: palette
    - type: field_group
      name: green
      label: Green
      fields:
      - type: include
        name: include_palette
        label: Palette
        template: palette
    - type: field_group
      name: purple
      label: Purple
      fields:
      - type: include
        name: include_palette
        label: Palette
        template: palette
- type: list
  name: disableKinds
  label: Disable Kinds
  description: Enable disabling of all pages of the specified Kinds.
  hidden: true
  config:
    source:
      type: custom
    options:
    - page
    - home
    - section
    - taxonomy
    - taxonomyTerm
    - RSS
    - sitemap
    - robotsTXT
    - '404'
    use_select: true
- type: boolean
  name: uglyURLs
  label: Ugly URLs
  description: When enabled, creates URL of the form /filename.html instead of /filename/.
  hidden: true
